# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker'
  - '.'

# Test by using it to run "docker build" on itself.
- name: 'gcr.io/$PROJECT_ID/docker'
  args:
  - 'build'
  - '.'

# Here are some things that can be done with this builder:

# Do the same build, but give the image a different name. Note that
# "docker-again" is absent from the "images" list below, so this image is built
# but is not pushed to the repository.
- name: 'gcr.io/$PROJECT_ID/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker-again'
  - '.'

# Get info about an image: run the "docker inspect" command on itself.
- name: 'gcr.io/$PROJECT_ID/docker'
  args: ['inspect', 'gcr.io/$PROJECT_ID/docker']

# Execute a container. The "busybox" container is executed within the docker
# build step to echo "Hello, world!"
- name: 'gcr.io/$PROJECT_ID/docker'
  args: ['run', 'busybox', 'echo', 'Hello, world!']

images:
- 'gcr.io/$PROJECT_ID/docker:latest'
