# In this directory, run the following command to build all cloud builders.
# gcloud builds submit

steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args: "./generate-config.sh"
  env: "REGISTRIES=${_REGISTRIES}"
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    # Triggers execute from the root of the repository, so the following
    # conditional enables this build config to work correctly both from the
    # repository root and from within the `Beta` directory.
    [[ -d Beta ]] && cd Beta
    today=$(date +%Y%m%d) # for dated images

    # Build each build step asynchronously and capture each buildid.
    declare -A build_ids
    for cfg in */cloudbuild.yaml; do
      step=$(dirname "${cfg}")

      buildid=$(gcloud builds submit --config=${cfg} --async \
          --substitutions=_YYYYMMDD=${today},_TRIGGER=${_TRIGGER} ${step} \
          | tee /tmp/${step} | grep QUEUED | awk '{ print $1 }')
      cat /tmp/${step} # Log output to main buildlog.

      build_ids[${step}]="${buildid}"
      echo "${step} buildID: ${buildid}"
    done

    # Now wait for builds to complete, failing if any single build fails.
    exitvalue=0
    for step in "${!build_ids[@]}"; do
      echo "Waiting for ${step} build..."
      ./wait-for-build.sh "${build_ids[$step]}" || exitvalue=1
    done
    exit $exitvalue
options:
  env:
  - 'TZ=EST5EDT'
timeout: 1200s
substitutions: # Default substitution values can be overridden on the command line.
  '_TRIGGER':    'manual'
  '_REGISTRIES': ''
tags:
- "${_TRIGGER}"
